# Generated by Django 3.2.5 on 2021-07-26 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aministre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=200, null=True, verbose_name='Prenom')),
                ('email', models.EmailField(max_length=300, verbose_name='Email')),
                ('adresse', models.CharField(max_length=300, null=True, verbose_name='Adresse')),
                ('telephone', models.IntegerField(null=True, verbose_name='Téléphone')),
                ('password', models.CharField(default='password', max_length=300, verbose_name='Mot de passe')),
            ],
            options={
                'verbose_name': 'client',
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=300, null=True, verbose_name='Adresse')),
                ('telephone', models.IntegerField(verbose_name='Téléphone')),
                ('couleur_js', models.CharField(max_length=60, null=True, verbose_name='code couleur Jours spécifiques')),
                ('couleur_conge', models.CharField(max_length=60, null=True, verbose_name='code couleur Jours off')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'responsable',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('duree_rdv', models.IntegerField(default=45, verbose_name='Durée des RDV dans ce service')),
                ('debut_pause', models.TimeField(null=True, verbose_name='Début de la pause')),
                ('fin_pause', models.TimeField(null=True, verbose_name='Fin de la pause')),
            ],
            options={
                'verbose_name': 'service',
            },
        ),
        migrations.CreateModel(
            name='ResponsableService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdv.responsable')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdv.service')),
            ],
            options={
                'verbose_name': 'Responsable de service',
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_r', models.DateField(verbose_name='Date Rdv')),
                ('heure_r', models.TimeField(verbose_name='Heure Rdv')),
                ('heure_f', models.TimeField(null=True, verbose_name='Heure de fin Rdv')),
                ('etat', models.CharField(default='En attente', max_length=30, null=True, verbose_name='Etat du Rdv')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdv.aministre')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rdv.responsable')),
            ],
            options={
                'verbose_name': 'rendez-vous',
                'verbose_name_plural': 'rendez-vous',
            },
        ),
    ]
