# Generated by Django 3.2.5 on 2021-07-27 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_d', models.DateField(verbose_name='Date debut evenement')),
                ('date_f', models.DateField(verbose_name='Date fin evenement')),
                ('heure_r', models.TimeField(null=True, verbose_name='Heure debut evenement')),
                ('heure_f', models.TimeField(null=True, verbose_name='Heure de fin evenement')),
                ('lieux', models.CharField(max_length=200, verbose_name='Lieux de evenement')),
            ],
        ),
        migrations.RenameModel(
            old_name='Aministre',
            new_name='Administre',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='evenement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rdv.evenement'),
        ),
    ]
