# Generated by Django 3.2.5 on 2021-07-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0002_auto_20210727_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='date_f',
            field=models.DateField(null=True, verbose_name='Date fin du RDV'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='date_r',
            field=models.DateField(verbose_name='Date debut Rdv'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='heure_r',
            field=models.TimeField(null=True, verbose_name='Heure debut Rdv'),
        ),
    ]
