# Generated by Django 3.2.5 on 2021-07-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0005_evenement_intitule'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='jours',
            field=models.CharField(max_length=20, null=True, verbose_name='Jour de la semaine'),
        ),
    ]
