# Generated by Django 3.2.5 on 2021-08-03 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rdv', '0006_evenement_jours'),
    ]

    operations = [
        migrations.AddField(
            model_name='administre',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='administre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdv', to='rdv.administre'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='evenement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evenement', to='rdv.evenement'),
        ),
    ]
