# Generated by Django 3.2.5 on 2021-08-09 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0008_rendezvous_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='debut_pause',
        ),
        migrations.RemoveField(
            model_name='service',
            name='duree_rdv',
        ),
        migrations.RemoveField(
            model_name='service',
            name='fin_pause',
        ),
    ]
