# Generated by Django 3.2.5 on 2021-08-09 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0009_auto_20210809_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='respnsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rdv.responsable'),
        ),
    ]
