# Generated by Django 3.2.5 on 2021-08-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0013_alter_responsable_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='respnsable',
            new_name='responsable',
        ),
    ]
