# Generated by Django 3.2.5 on 2021-09-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0015_administrateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='ville',
            field=models.CharField(max_length=50, null=True, verbose_name="Ville de l'évenement"),
        ),
    ]
