# Generated by Django 3.2.5 on 2021-09-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0016_evenement_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='validite',
            field=models.CharField(max_length=10, null=True, verbose_name='validté de la reservation'),
        ),
    ]
